#!/bin/bash

echo -e "\nHINT: Be sure to compile project with IDEA first\n"

echo -e "=== RetrieveModuleInfo"
java -modulepath ../target/production/playground:../target/production/playground-dependent  \
    -m anothermodule/de.exxcellent.anothermodule.RetrieveModuleInfo


echo -e "\n\n=== TestJigsawSPI"
java -modulepath ../target/production/playground:../target/production/playground-dependent  \
    -m anothermodule/de.exxcellent.anothermodule.TestJigsawSPI
