= Java 9 - What's hot, whats not
Benjamin Schmid <benjamin.schmid@exxcellent.de>

== Introduction
This repository & RevealJS HTML slide presentation tries to give an overview
over the improvments coming with Java 9.

It's based on the current state as of 2016-07-01.

== Contents

[cols="1,3"]
|===
|`presentation`         | A short RevealJS based presentation. Just open `index.html`
|`playground`           | Extensive collection of various one-class code examples illustrating the changes. Start here for your experiments!
|`playground-dependent` | Another Jigsaw module depending on `playground` and
      demonstrating Service Provider with modules.
|`run-with-modules`     | Bash script demonstrating how to compile & run the example
      as modules using the new Java9 command line parameters
|===

== Getting started
1. Install Java 9 EAP
2. Ensure `JAVA_HOME` and `PATH` points to Java 9
3. Open project with IntelliJ IDEA 2016.2+ or run `run-with-modules`

----
$ env | grep JAVA_HOME
JAVA_HOME=/usr/lib/jvm/java-9-oracle
$ javac -version
javac 9-ea
$ java -version
java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+123)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+123, mixed mode)
----

